services:
- type: pserv
  name: elasticsearch
  env: docker
  plan: free
  #disk:
  #  name: esdata
  #  mountPath: /usr/share/elasticsearch/data
  #  sizeGB: 10
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms256m -Xmx256m"
    #value: "-Xms512m -Xmx512m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
